#!/bin/sh
#
# @name qav250
#
# @type Quadrotor X
#

set VEHICLE_TYPE mc

set MIXER_AUX pass

set PWM_AUX_OUT 1234
set PWM_AUX_RATE 50
set PWM_OUT 1234

set MIXER quad_x

param set EKF2_AID_MASK 24
param set EKF2_EV_DELAY 0 
param set EKF2_HGT_MODE 3 

param set NAV_ACC_RAD 2

param set RTL_RETURN_ALT 1.5
param set RTL_DESCEND_ALT 1.5
param set RTL_LAND_DELAY 0

param set BAT_N_CELLS 3

param set IMU_GYRO_CUTOFF 120
param set MC_DTERM_CUTOFF 45

param set MC_AIRMODE 1
param set MC_PITCHRATE_D 0.0012
param set MC_PITCHRATE_I 0.35
param set MC_PITCHRATE_MAX 1200
param set MC_PITCHRATE_P 0.082
param set MC_PITCH_P 8
param set MC_ROLLRATE_D 0.0012
param set MC_ROLLRATE_I 0.3
param set MC_ROLLRATE_MAX 1200
param set MC_ROLLRATE_P 0.076
param set MC_ROLL_P 8
param set MC_YAWRATE_I 0.3
param set MC_YAWRATE_MAX 600
param set MC_YAWRATE_P 0.25
param set MC_YAW_P 4

param set MPC_MANTHR_MIN 0
param set MPC_MAN_TILT_MAX 60
param set MPC_THR_CURVE 1
param set MPC_THR_HOVER 0.25
param set MPC_THR_MIN 0.05
param set MPC_Z_VEL_I 0.085

param set PWM_MAX 1950
param set PWM_MIN 1050

param set PWM_RATE 0
param set RC_FLT_CUTOFF 0
param set THR_MDL_FAC 0.3